services:
  - type: web
    name: ai-interview-coach
    runtime: python
    pythonVersion: 3.10.13
    plan: free
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
