services:
  - type: web
    name: ai-interview-coach
    env: python
    buildCommand: pip install --upgrade pip && pip install -r $RENDER_GIT_REPO_DIR/requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
